# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  subscription: 'subscription'

stages:
- stage: build
  displayName: 'Build and test the website'
  jobs:
  - job: run_build
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - script: echo Build
      displayName: 'First step in building the website skeleton'

- stage: build_integration
  displayName: 'Build the integration environment resource group'
  dependsOn: build
  jobs:
  - template: ci/templates/create-resource-group.yml
    parameters:
      name: create_infrastructure
      displayName: 'First step in building the integration infrastructure'
      vmImage: 'Ubuntu-16.04'
      resourceGroupName: integration
      subscription: $(subscription)

- stage: deploy_app_service_to_integration
  displayName: 'Deploy the app service to the integration environment'
  dependsOn: build_integration
  jobs:
  - job: deploy_app_service_to_integration
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - task: AzureResourceGroupDeployment@2
      inputs:
        azureSubscription: '$(subscription)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'integration-rg'
        location: 'UK South'
        templateLocation: 'URL of the file'
        csmFileLink: 'https://raw.githubusercontent.com/solstarz/simpleazureservice/master/SimpleAzureAppService/WebSite.json'
        overrideParameters: '-hostingPlanName integration-webfarm'
        deploymentMode: 'Incremental'

- stage: deploy_to_integration
  displayName: 'Deploy the website to the integration environment'
  dependsOn: deploy_app_service_to_integration
  jobs:
  - job: deploy_artefacts_to_integration
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - script: echo Deploy Website to Integration
      displayName: 'First step in deploying the website to integration'

- stage: run_system_quality_tests
  displayName: 'Run the system quality tests'
  dependsOn: deploy_to_integration
  jobs:
  - job: run_non_functional_tests
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - script: echo Run system quality tests
      displayName: 'Running the system quality tests'

- stage: build_test
  displayName: 'Build the test environment'
  dependsOn: deploy_to_integration
  jobs:
  - template: ci/templates/create-resource-group.yml
    parameters:
      name: create_infrastructure
      displayName: 'First step in building the test infrastructure'
      vmImage: 'Ubuntu-16.04'
      resourceGroupName: testing
      subscription: $(subscription)

- stage: deploy_app_service_to_test
  displayName: 'Deploy the app service to the test environment'
  dependsOn: build_test
  jobs:
  - job: deploy_app_service_to_test
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - task: AzureResourceGroupDeployment@2
      inputs:
        azureSubscription: '$(subscription)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'test-rg'
        location: 'UK South'
        templateLocation: 'URL of the file'
        csmFileLink: 'https://raw.githubusercontent.com/solstarz/simpleazureservice/master/SimpleAzureAppService/WebSite.json'
        overrideParameters: '-hostingPlanName test-webfarm'
        deploymentMode: 'Incremental'

- stage: deploy_to_test
  displayName: 'Deploy the website to the test environment'
  dependsOn: deploy_app_service_to_test
  jobs:
  - job: deploy_artefacts_to_test
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - script: echo Deploy Website to Test
      displayName: 'First step in deploying the website to test'

- stage: build_demo
  displayName: 'Build the demo environment'
  dependsOn: deploy_to_test
  jobs:
  - template: ci/templates/create-resource-group.yml
    parameters:
      name: create_infrastructure
      displayName: 'First step in building the demo infrastructure'
      vmImage: 'Ubuntu-16.04'
      resourceGroupName: demonstration
      subscription: $(subscription)

- stage: deploy_to_demo
  displayName: 'Deploy the website to the demo environment'
  dependsOn: build_demo
  jobs:
  - job: deploy_artefacts_to_demo
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - script: echo Deploy Website to Demo
      displayName: 'First step in deploying the website to demo'
